server:
  port: 8080

spring: 
  application:
    name: msvc-gateway
  cloud:
    discovery:
      enabled: true
    routes:
      - id: pacientes 
        uri: http://localhost:8090
        predicates:
          - Path=/api/v1/pacientes/**


eureka: 
  client:
    register-with-eureka: false
    fetch-registry: false